# permissions for end users to view osushis.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: osushi-viewer-role
rules:
- apiGroups:
  - cache.my.domain
  resources:
  - osushis
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cache.my.domain
  resources:
  - osushis/status
  verbs:
  - get
