# permissions for end users to edit osushis.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: osushi-editor-role
rules:
- apiGroups:
  - cache.my.domain
  resources:
  - osushis
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.my.domain
  resources:
  - osushis/status
  verbs:
  - get
